import Navbar from '@/components/navbar/Navbar'

import { Inter } from 'next/font/google'
import { NextAuthProvider } from '../Providers'
// import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayoutLogin({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <NextAuthProvider>
          <Navbar/>
          {children}
        </NextAuthProvider> 
      </body>
    </html>
  )
}